// src/app/icons.ts
import { IconName, IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { 
  faArrowDown, faArrowLeft, faArrowRight, faArrowUp, 
  faArrowUpRightFromSquare, faArrowsRotate, 
  faBackwardFast, faBars, faBell, 
  faBookmark, faBrain, faBriefcase, faBuilding, faCaretDown, faCaretLeft, faCaretRight, 
  faCaretUp, faCartShopping, faChartLine, faChartPie, faCheck, faChevronCircleDown, 
  faChevronCircleLeft, faChevronCircleRight, faChevronCircleUp, faChevronDown, 
  faChevronLeft, faChevronUp, faCircle, faCircleCheck, faCircleExclamation, 
  faCircleInfo, faCircleMinus, faCirclePlay, faCirclePlus, faCircleQuestion, 
  faCircleXmark, faComment, faComments, faCompass, faCompress, faCopy, faDollarSign, 
  faEllipsis, faEllipsisVertical, faEnvelope, faExpand, faEye, faEyeSlash, faFile, faFileLines, faFlag, 
  faFolder, faForwardFast, faGear, faGripLines, 
  faGripLinesVertical, faHeart, faHouse, faLightbulb, faLink, faList, 
  faLocationPin, faLock, faLockOpen, faMagnifyingGlass, faMagnifyingGlassMinus, 
  faMagnifyingGlassPlus, faMinus, faMobile, faNewspaper, 
  faPaperPlane, faPause, faPen, faPhone, faPlay, faPlus, faPrint, faReply, 
  faRotateLeft, faShare, faStar, faThumbTack, faThumbsDown, faThumbsUp, 
  faTrash, faTriangleExclamation, faUpload, faUser, faUsers, faVolumeLow, 
  faVolumeMute, faVolumeOff, faVolumeUp, faWallet, faX 
} from '@fortawesome/free-solid-svg-icons';

import { 
  faAddressBook, faAddressCard, faBookmark as faBookmarked, 
  faCalendarAlt, faEnvelope as Envelope, faFileAlt, 
  faFrown, faSmile, faQuestionCircle, faStarHalf 
} from '@fortawesome/free-regular-svg-icons';

export const faIconsList: { label: string, icon: IconName, value: IconDefinition }[] = [
  { label: 'add', icon: 'plus', value: faPlus },
  { label: 'add circle', icon: 'circle-plus', value: faCirclePlus },
  { label: 'bell', icon: 'bell', value: faBell },
  { label: 'calendar', icon: 'calendar', value: faCalendarAlt },
  { label: 'cart', icon: 'cart-shopping', value: faCartShopping },
  { label: 'case', icon: 'briefcase', value: faBriefcase },
  { label: 'check', icon: 'check', value: faCheck },
  { label: 'chat', icon: 'comment', value: faComment },
  { label: 'close', icon: 'xmark', value: faX },
  { label: 'close circle', icon: 'circle-xmark', value: faCircleXmark },
  { label: 'compass', icon: 'compass', value: faCompass },
  { label: 'conversation', icon: 'comments', value: faComments },
  { label: 'copy', icon: 'copy', value: faCopy },
  { label: 'download', icon: 'arrow-down', value: faArrowDown },
  { label: 'drag horizontal', icon: 'grip-lines', value: faGripLines },
  { label: 'drag vertical', icon: 'grip-lines-vertical', value: faGripLinesVertical },
  { label: 'pen', icon: 'pen', value: faPen },
  { label: 'email', icon: 'envelope', value: faEnvelope },
  { label: 'expand', icon: 'expand', value: faExpand },
  { label: 'external link', icon: 'arrow-up-right-from-square', value: faArrowUpRightFromSquare },
  { label: 'file', icon: 'file', value: faFile },
  { label: 'file alt', icon: 'file-alt', value: faFileLines },
  { label: 'filter', icon: 'filter', value: faFile },
  { label: 'flag', icon: 'flag', value: faFlag },
  { label: 'flag pennant', icon: 'flag', value: faFlag }, // No direct Free counterpart
  { label: 'folder', icon: 'folder', value: faFolder },
  { label: 'folder user', icon: 'folder-user', value: faFolder }, // No direct Free counterpart
  { label: 'group', icon: 'users', value: faUsers },
  { label: 'hamburger menu', icon: 'bars', value: faBars },
  { label: 'kebab menu', icon: 'ellipsis-vertical', value: faEllipsisVertical },
  { label: 'lightbulb', icon: 'lightbulb', value: faLightbulb },
  { label: 'link', icon: 'link', value: faLink },
  { label: 'list', icon: 'list', value: faList },
  { label: 'location', icon: 'location-pin', value: faLocationPin },
  { label: 'meatball menu', icon: 'ellipsis', value: faEllipsis },
  { label: 'minus', icon: 'minus', value: faMinus },
  { label: 'minus circle', icon: 'circle-minus', value: faCircleMinus },
  { label: 'mobile', icon: 'mobile', value: faMobile },
  { label: 'money', icon: 'dollar-sign', value: faDollarSign }, 
  { label: 'phone', icon: 'phone', value: faPhone },
  { label: 'pin', icon: 'thumbtack', value: faThumbTack },
  { label: 'print', icon: 'print', value: faPrint },
  { label: 'question mark', icon: 'question-circle', value: faCircleQuestion },
  { label: 'refresh', icon: 'sync', value: faArrowsRotate },
  { label: 'send', icon: 'paper-plane', value: faPaperPlane },
  { label: 'search', icon: 'search', value: faMagnifyingGlass },
  { label: 'settings', icon: 'cogs', value: faGear },
  { label: 'share', icon: 'share', value: faShare },
  { label: 'sync', icon: 'sync', value: faGear }, 
  { label: 'trash', icon: 'trash', value: faTrash },
  { label: 'undo', icon: 'undo', value: faRotateLeft },
  { label: 'upload', icon: 'upload', value: faUpload }, 
  { label: 'user', icon: 'user', value: faUser },
  { label: 'home', icon: 'home', value: faHouse },
  { label: 'status dashboard', icon: 'check-circle', value: faCircleCheck },
  { label: 'reporting', icon: 'chart-pie', value: faChartPie },
  { label: 'growth', icon: 'chart-line', value: faChartLine },
  { label: 'home office', icon: 'building', value: faBuilding },
  { label: 'account', icon: 'wallet', value: faWallet },
  { label: 'news', icon: 'newspaper', value: faNewspaper },
  { label: 'support', icon: 'question-circle', value: faQuestionCircle },
  { label: 'education', icon: 'brain', value: faBrain }, 
  { label: 'play', icon: 'play', value: faPlay },
  { label: 'pause', icon: 'pause', value: faPause },
  { label: 'replay', icon: 'reply', value: faReply },
  { label: 'volume up', icon: 'volume-up', value: faVolumeUp },
  { label: 'volume down', icon: 'volume-down', value: faVolumeLow },
  { label: 'volume mute', icon: 'volume-mute', value: faVolumeMute },
  { label: 'volume off', icon: 'volume-off', value: faVolumeOff },
  { label: 'fast forward', icon: 'fast-forward', value: faForwardFast },
  { label: 'rewind', icon: 'wind', value: faBackwardFast },
]
